---

- name: Provision Terraform for AAP-HashiCorp integrated demo
  hosts: "{{ groups['aap_hashi_terraform'][0] }}"
  tags: terraform_provision

  roles:
    - name: terraform_provision

- name: Pull certs back from vault host
  hosts: "{{ groups['aap_hashi_vault'][0] }}"

  tasks:

    - name: Find all certs
      ansible.builtin.find:
        paths: "{{ vault_terraform_certdir }}"
        patterns: "*"
      register: cert_files

    - name: Make sure that the local_certdir directory exists
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ local_certdir }}"
        state: directory
        mode: '0755'

    - name: Copy certs back
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ local_certdir }}/"
        flat: true
      loop: "{{ cert_files.files }}"

- name: Run installation for terraform
  hosts: "{{ groups['aap_hashi_terraform'][0] }}"
  tags: terraform_install

  vars:
    ansible_user: "{{ terraform_user }}"

  roles:
    - name: terraform_install

  tasks:

    - name: Copy admin token back
      ansible.builtin.fetch:
        src: "{{ terraform_install_admin_token }}"
        dest: "{{ local_certdir }}/terraform-admin_token.txt"
        flat: true

    - name: Copy admin login back
      ansible.builtin.fetch:
        src: "{{ terraform_install_admin_login }}"
        dest: "{{ local_certdir }}/terraform-admin_login.txt"
        flat: true

...
